# Generated by Django 5.2.1 on 2025-05-26 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField(blank=True)),
                ('author', models.TextField(blank=True)),
                ('text', models.TextField(blank=True)),
                ('published', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
