# Generated by Django 5.2.1 on 2025-06-14 03:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre_name', models.CharField()),
            ],
        ),
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('artist_name', models.CharField()),
                ('genre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.genre')),
            ],
        ),
        migrations.CreateModel(
            name='Song',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('song_name', models.CharField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.artist')),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField()),
                ('last_name', models.CharField()),
                ('fav_artist', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.artist')),
                ('fav_genre', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.genre')),
                ('fav_song', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='project.song')),
            ],
        ),
    ]
