# Generated by Django 5.2.1 on 2025-06-21 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0003_badge_badge_name_collection'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='badge',
            name='badge_holder',
        ),
    ]
