# Generated by Django 5.2.1 on 2025-06-21 15:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0004_remove_badge_badge_holder'),
    ]

    operations = [
        migrations.CreateModel(
            name='SquishPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.profile')),
                ('squish', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='project.squishmallow')),
            ],
        ),
    ]
