# Generated by Django 5.2.1 on 2025-06-21 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0005_squishphoto'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='badges',
            field=models.ManyToManyField(blank=True, to='project.badge'),
        ),
    ]
