# Generated by Django 5.2.1 on 2025-05-27 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('city', models.TextField(blank=True)),
                ('email_address', models.EmailField(max_length=254)),
                ('profile_image_url', models.TextField()),
            ],
        ),
    ]
